;
(function(){
    $(function(){
        window._bd_share_config={
            "common":{
                "bdSnsKey":{},
                "bdText":"",
                "bdMini":"2",
                "bdMiniList":false,
                "bdPic":"",
                "bdStyle":"0",
                "bdSize":"32"
            },
            "share":{},
            "image":{
                "viewList":["tsina","qzone","tqq","renren","weixin"],
                "viewText":"∑÷œÌµΩ£∫","viewSize":"16"
            },
            "selectShare":{
                "bdContainerClass":null,
                "bdSelectMiniList":["tsina","qzone","tqq","renren","weixin"]
            }
        };
        with(document)0[(getElementsByTagName('head')[0]||body)
            .appendChild(createElement('script'))
            .src='http://bdimg.share.baidu.com/static/api/js/share.js?v=89860593.js?cdnversion='+~(-new Date()/36e5)];

    });
})();